# Mix RLN Spam Protection Plugin - Module interop test
# Copyright (c) 2025 vacp2p
# Licensed under either of Apache License 2.0 or MIT license.

## Go/no-go interop gate: a proof generated by the liblogos_rln_module
## logos-core module (fixtures in this directory) must verify under this
## plugin's zerokit verifier.
##
## Run (same linkage as the nimble `test` task):
##   nim c -r --passL:vendor/librln_mix_v2.0.0.a --passL:-lm \
##     tests/interop/test_module_interop.nim
##
## Fixtures:
##   module_proof.json    - real generate_proof reply from the module
##   merkle_snapshot.json - registry Merkle snapshot (root + valid_roots)
##   meta.json            - signal, rln_identifier, epoch parameters
##
## This test targets the rln_interface verify path directly and never
## compares the fixture epoch against wall-clock time, so the vector
## cannot rot as time passes.

import std/[json, os]
import results
import ../../src/mix_rln_spam_protection/types
import ../../src/mix_rln_spam_protection/rln_interface

const
  FixtureDir = currentSourcePath().parentDir()
  Groth16Size = 128
  BlobSize = 1 + Groth16Size + 1 + 5 * 32 # canonical zerokit proof blob: 290

proc pass(msg: string) =
  echo "PASS: ", msg

proc fail(msg: string) {.noreturn.} =
  echo "FAIL: ", msg
  quit(1)

proc check(cond: bool, msg: string) =
  if cond:
    pass(msg)
  else:
    fail(msg)

proc hexToBytes(hex, what: string): seq[byte] =
  result = fromHex(hex)
  if result.len == 0:
    fail(what & ": invalid or empty hex")

proc hexTo32(hex, what: string): array[32, byte] =
  let bytes = hexToBytes(hex, what)
  if bytes.len != 32:
    fail(what & ": expected 32 bytes, got " & $bytes.len)
  for i in 0 ..< 32:
    result[i] = bytes[i]

proc slice32(data: seq[byte], offset: int): array[32, byte] =
  for i in 0 ..< 32:
    result[i] = data[offset + i]

let
  moduleReply = parseFile(FixtureDir / "module_proof.json")
  snapshot = parseFile(FixtureDir / "merkle_snapshot.json")
  meta = parseFile(FixtureDir / "meta.json")

let
  signal = hexToBytes(meta["signal_hex"].getStr, "signal_hex")
  rlnIdentifier: RlnIdentifier =
    hexTo32(meta["rln_identifier_hex"].getStr, "rln_identifier_hex")

# --- 1/2. Decode the canonical proof blob and cross-check the JSON fields ---

let blob = hexToBytes(moduleReply["proof"].getStr, "proof blob")
check(blob.len == BlobSize, "canonical proof blob is " & $BlobSize & " bytes")
check(blob[0] == 0x00'u8, "leading blob version byte is 0x00")
check(blob[1 + Groth16Size] == 0x00'u8,
  "field-element section version byte is 0x00")

let
  blobRoot = slice32(blob, 130)
  blobExternalNullifier = slice32(blob, 162)
  blobShareX = slice32(blob, 194)
  blobShareY = slice32(blob, 226)
  blobNullifier = slice32(blob, 258)

let
  jsonRoot = hexTo32(moduleReply["root"].getStr, "root")
  jsonExternalNullifier =
    hexTo32(moduleReply["external_nullifier"].getStr, "external_nullifier")
  jsonShareX = hexTo32(moduleReply["share_x"].getStr, "share_x")
  jsonShareY = hexTo32(moduleReply["share_y"].getStr, "share_y")
  jsonNullifier = hexTo32(moduleReply["nullifier"].getStr, "nullifier")

check(blobRoot == jsonRoot, "blob root == JSON root")
check(blobExternalNullifier == jsonExternalNullifier,
  "blob external_nullifier == JSON external_nullifier")
check(blobShareX == jsonShareX, "blob share_x == JSON share_x")
check(blobShareY == jsonShareY, "blob share_y == JSON share_y")
check(blobNullifier == jsonNullifier, "blob nullifier == JSON nullifier")

let snapshotRoot = hexTo32(snapshot["root"].getStr, "snapshot root")
check(jsonRoot == snapshotRoot, "proof root == merkle snapshot root")

# --- 3. Epoch: module u64 index -> plugin 32-byte epoch (u64 LE, padded) ---

let epochIndex = uint64(moduleReply["epoch"].getInt)
let epoch32: Epoch = uint64ToField(epochIndex)
check(epochToUint64(epoch32) == epochIndex,
  "epoch32 round-trips the module epoch index " & $epochIndex)

var proof = RateLimitProof(
  merkleRoot: blobRoot,
  epoch: epoch32,
  shareX: blobShareX,
  shareY: blobShareY,
  nullifier: blobNullifier,
)
for i in 0 ..< Groth16Size:
  proof.proof[i] = blob[1 + i]

# --- 4. External nullifier construction gate ---

let extNullifierRes = computeExternalNullifier(epoch32, rlnIdentifier)
if extNullifierRes.isErr:
  fail("computeExternalNullifier errored: " & extNullifierRes.error)
if extNullifierRes.get != jsonExternalNullifier:
  echo "FAIL: CONSTRUCTION DIVERGENCE - computeExternalNullifier(epoch32, " &
    "rln_identifier) does not match the module's external_nullifier."
  echo "  plugin: ", extNullifierRes.get.toHex()
  echo "  module: ", jsonExternalNullifier.toHex()
  echo "  The plugin and liblogos_rln_module external-nullifier " &
    "constructions still diverge; module proofs CANNOT verify here."
  quit(1)
pass("computeExternalNullifier(epoch32, rln_identifier) == module " &
  "external_nullifier")

# --- 5. Verify the module proof under the plugin's zerokit verifier ---

let instanceRes = newRLNInstance()
if instanceRes.isErr:
  fail("newRLNInstance failed: " & instanceRes.error)
let instance = instanceRes.get

var validRoots: seq[MerkleNode]
for rootNode in snapshot["valid_roots"]:
  validRoots.add(MerkleNode(hexTo32(rootNode.getStr, "valid_roots[]")))
check(validRoots.len > 0, "merkle snapshot provides " & $validRoots.len &
  " valid roots")

let verifyRes = verifyRlnProof(instance, proof, rlnIdentifier, signal,
  validRoots)
if verifyRes.isErr:
  fail("verifyRlnProof errored: " & verifyRes.error)
check(verifyRes.get,
  "module-generated proof VERIFIES under the plugin zerokit verifier")

# --- 6. Tampered signal must not verify ---

var tamperedSignal = signal
tamperedSignal[0] = tamperedSignal[0] xor 0x01'u8
let tamperRes = verifyRlnProof(instance, proof, rlnIdentifier, tamperedSignal,
  validRoots)
check(tamperRes.isErr or not tamperRes.get,
  "tampered signal is REJECTED (" &
    (if tamperRes.isErr: "error: " & tamperRes.error else: "returned false") &
    ")")

echo "ALL INTEROP ASSERTIONS PASSED: module proofs are compatible with the " &
  "plugin verifier"
